### GET THE CARTS OF A USER
GET {{LOCAL}}/carts
Authorization: Bearer {{TOKEN}}

### FIND A CART BY CODE
GET {{LOCAL}}/carts/code/23ed8420-a559-4f96-9e7c-dc462a2da472
Authorization: Bearer {{TOKEN}}

### SAVE A CART
POST {{LOCAL}}/carts
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "visibility": "PUBLIC",
  "products": [
    {
      "product": "64e42276353882f64eb60c3a",
      "quantity": 2,
      "order": 1,
      "options": [
        {
          "option": "64e404f8d5af2b630b1429cc",
          "selected": "64e404f8d5af2b630b1429c6"
        }
      ]
    }
  ]
}

### CLONE A CART
POST {{LOCAL}}/carts/clone/1f9a72eb-008c-471e-8bb8-efdfed98a6c7
Authorization: Bearer {{TOKEN}}

### UPDATE A CART
PUT {{LOCAL}}/carts/64f2bd1369ec15ce6dfe1533
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "visibility": "PRIVATE",
  "products": [
    {
      "product": "64e42276353882f64eb60c3a",
      "quantity": 1,
      "order": 1,
      "options": [
        {
          "option": "64e404f8d5af2b630b1429cc",
          "selected": "64e404f8d5af2b630b1429c6"
        }
      ]
    }
  ]
}

### DELETE A CART
DELETE {{LOCAL}}/carts/64f2bd1369ec15ce6dfe1533
Authorization: Bearer {{TOKEN}}

### DELETE ALL CARTS
DELETE {{LOCAL}}/carts/all
Authorization: Bearer {{TOKEN}}